# Generated by Django 2.0.6 on 2018-06-05 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('kriisis_id', models.IntegerField(unique=True)),
                ('name', models.TextField()),
                ('children', models.ManyToManyField(blank=True, related_name='parents', to='scraper.Category')),
                ('subscribed_users', models.ManyToManyField(related_name='subscribed_categories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('kriisis_id', models.IntegerField(unique=True)),
                ('item_name', models.TextField(verbose_name='item name')),
                ('item_description', models.TextField(verbose_name='item description')),
                ('price', models.FloatField()),
                ('image_url', models.TextField(verbose_name='image url')),
                ('telegram_image_file_id', models.TextField(blank=True, verbose_name='telegram image file id')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='scraper.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('kriisis_id', models.IntegerField(unique=True)),
                ('name', models.TextField()),
                ('image_url', models.TextField()),
                ('subscribed_users', models.ManyToManyField(related_name='subscribed_shops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='discount',
            name='shops',
            field=models.ManyToManyField(related_name='discounts', to='scraper.Shop'),
        ),
    ]
