# Generated by Django 2.0.6 on 2018-06-05 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subscribed_users',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='subscribed_users',
        ),
        migrations.AddField(
            model_name='category',
            name='subscribed_profiles',
            field=models.ManyToManyField(related_name='subscribed_categories', to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='shop',
            name='subscribed_profiles',
            field=models.ManyToManyField(related_name='subscribed_shops', to='accounts.Profile'),
        ),
    ]
